default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: builtcode_challenge_development
  user: jafer
  password: pompeu76

test:
  <<: *default
  database: builtcode_challenge_test
  user: jafer
  password: pompeu76

production:
  <<: *default
  database: builtcode_challenge_production
  username: builtcode_challenge
  password: <%= ENV['BUILTCODE_CHALLENGE_DATABASE_PASSWORD'] %>
